### PR TITLE
update impact observatory lulc with data for new years

### PR DESCRIPTION
**Pull request by Dorothyrono**

### CODE REVIEW

**Comment by batic** [comment]
😍

**Review by chorng — APPROVED** [review]

**Comment by Dorothyrono** [comment]
It seems the changes in this merge were not deployed , the [page ](https://collections.sentinel-hub.com/impact-observatory-lulc-map/) was not updated yet.

@zansinergise  do you know if something changed in deploy pipeline, or do you see something that went wrong ?

(testing a deploy of the main branch locally works and the changes are shown)

**Comment by zansinergise** [comment]
I honestly have no idea why the changes are not live. Tagging @zcernigoj if you maybe have an idea

**Comment by zcernigoj** [comment]
The webhook successfully triggered the deployment, so I'm not sure why the changes are not visible.

We can try to prepare a new MR with some other changes that might get these changes redeployed along with the changes in that MR.

**Comment by Dorothyrono** [comment]
The  solution worked.

After merging some other new changes

the changes for this page are now live .

**Comment by zcernigoj** [comment]
The page is now updated properly. The update for all of the pages might take some more time.

I guess this was a single occurrence.

**Pull request merged**
